/*
 * Interface.java
 *
 * Created on Mar 7, 2012, 11:06:04 AM
 */

package ibms;
import java.awt.event.*;


/**
 *
 * @author Ben
 */
public class Interface extends javax.swing.JPanel {

    /** Creates new form Interface */
    public Interface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generate = new javax.swing.JButton();
        requestholiday = new javax.swing.JButton();
        view = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        greeting = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(100, 200));

        generate.setLabel("Generate Roster");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        requestholiday.setLabel("Request Holiday");

        view.setLabel("View Roster");

        edit.setLabel("Edit Roster");

        greeting.setText("Welcome!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(greeting)
                        .add(0, 46, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, requestholiday, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, edit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, view, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .add(generate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(greeting)
                .add(14, 14, 14)
                .add(generate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(view)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(edit)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(requestholiday)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton generate;
    private javax.swing.JLabel greeting;
    private javax.swing.JButton requestholiday;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

}
