/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JourneyPlannerInterface.java
 *
 * Created on Apr 18, 2012, 12:07:36 PM
 */

package ibms;

/**
 *
 * @author Ben
 */
public class JourneyPlannerInterface extends javax.swing.JFrame {

    /** Creates new form JourneyPlannerInterface */
    public JourneyPlannerInterface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    fromAreaDropdown = new javax.swing.JComboBox();
    fromBusStopDropdown = new javax.swing.JComboBox();
    toAreaDropdown = new javax.swing.JComboBox();
    toBusStopDropdown = new javax.swing.JComboBox();
    toAreaLabel = new javax.swing.JLabel();
    toBusStopLabel = new javax.swing.JLabel();
    fromAreaLabel = new javax.swing.JLabel();
    fromBusStopLabel = new javax.swing.JLabel();
    fromLabel = new javax.swing.JLabel();
    toLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    outputArea = new javax.swing.JTextArea();
    submitButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    jLabel1.setText("Journey Planner");

    fromAreaDropdown.setModel(new javax.swing.DefaultComboBoxModel(BusStopInfo.getAreaNames()));
    fromAreaDropdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fromAreaDropdownActionPerformed(evt);
      }
    });

    fromBusStopDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Item 1", "Item 2", "Item 3", "Item 4" }));
    fromBusStopDropdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fromBusStopDropdownActionPerformed(evt);
      }
    });

    toAreaDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stockport", "Romiley", "Compstall", "Marple", "Offerton", "Strines", "New Mills", "Birch Vale", "HayField", "Newtown", "Low Leighton", "Thornsett", "Glossop" }));
    toAreaDropdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        toAreaDropdownActionPerformed(evt);
      }
    });

    toBusStopDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Item 1", "Item 2", "Item 3", "Item 4" }));
    toBusStopDropdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        toBusStopDropdownActionPerformed(evt);
      }
    });

    toAreaLabel.setText("Area");

    toBusStopLabel.setText("Bus Stop:");

    fromAreaLabel.setText("Area:");

    fromBusStopLabel.setText("Bus Stop:");

    fromLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    fromLabel.setText("From:");

    toLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    toLabel.setText("To:");

    outputArea.setColumns(20);
    outputArea.setRows(5);
    jScrollPane1.setViewportView(outputArea);

    submitButton.setText("Submit");
    submitButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        submitButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(fromLabel)
              .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
              .add(toLabel)
              .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(fromBusStopLabel)
                  .add(fromAreaLabel))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(fromAreaDropdown, 0, 138, Short.MAX_VALUE)
                  .add(fromBusStopDropdown, 0, 138, Short.MAX_VALUE)))
              .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(toBusStopLabel)
                  .add(toAreaLabel))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(toAreaDropdown, 0, 138, Short.MAX_VALUE)
                  .add(toBusStopDropdown, 0, 138, Short.MAX_VALUE)))))
          .add(layout.createSequentialGroup()
            .add(55, 55, 55)
            .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .add(18, 18, 18)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
          .add(layout.createSequentialGroup()
            .add(jLabel1)
            .add(40, 40, 40)
            .add(fromLabel)
            .add(18, 18, 18)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(fromAreaLabel)
              .add(fromAreaDropdown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(fromBusStopLabel)
              .add(fromBusStopDropdown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(18, 18, 18)
            .add(toLabel)
            .add(18, 18, 18)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(toAreaLabel)
              .add(toAreaDropdown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(toBusStopLabel)
              .add(toBusStopDropdown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(18, 18, 18)
            .add(submitButton)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    String fArea;
    String fBusStop;
    String tArea;
    String tBusStop;

    private void toAreaDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAreaDropdownActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox cb = (javax.swing.JComboBox) evt.getSource();
        tArea = (String)cb.getSelectedItem();
        box4Updater(tArea);

    }//GEN-LAST:event_toAreaDropdownActionPerformed

    private void toBusStopDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBusStopDropdownActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox cb = (javax.swing.JComboBox) evt.getSource();
        tBusStop = (String)cb.getSelectedItem();
    }//GEN-LAST:event_toBusStopDropdownActionPerformed

    private void fromAreaDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromAreaDropdownActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox cb = (javax.swing.JComboBox) evt.getSource();
        fArea = (String)cb.getSelectedItem();
        System.out.println("From area: " + fArea);
        box2Updater(fArea);
    }//GEN-LAST:event_fromAreaDropdownActionPerformed

    private void fromBusStopDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromBusStopDropdownActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox cb = (javax.swing.JComboBox) evt.getSource();
        fBusStop = (String)cb.getSelectedItem();
    }//GEN-LAST:event_fromBusStopDropdownActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        outputArea.setText(JourneyPlanner.getRoutes(fArea, fBusStop, tArea,
      tBusStop));
    }//GEN-LAST:event_submitButtonActionPerformed


    
    private void box2Updater(String area) {

        System.out.println("Area: " + area);
        int areaNum = BusStopInfo.findAreaByName(area);
        System.out.println("Area Num: " + areaNum);
        int [] busStopsInArea = BusStopInfo.getBusStopsInArea(areaNum);
        String busStopName;

        fromBusStopDropdown.removeAllItems();
        for(int i = 0; i <= busStopsInArea.length; i ++) {
            busStopName = BusStopInfo.getFullName(busStopsInArea[i]);
            fromBusStopDropdown.addItem(busStopName);
        }

    }
    private void box4Updater(String area) {

        int areaNum = BusStopInfo.findAreaByName(area);
        int [] busStopsInArea = BusStopInfo.getBusStopsInArea(areaNum);
        String busStopName;

        toBusStopDropdown.removeAllItems();
        for(int i = 0; i <= busStopsInArea.length; i ++) {
            busStopName = BusStopInfo.getFullName(busStopsInArea[i]);
            toBusStopDropdown.addItem(busStopName);
        }

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JourneyPlannerInterface().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox fromAreaDropdown;
  private javax.swing.JLabel fromAreaLabel;
  private javax.swing.JComboBox fromBusStopDropdown;
  private javax.swing.JLabel fromBusStopLabel;
  private javax.swing.JLabel fromLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea outputArea;
  private javax.swing.JButton submitButton;
  private javax.swing.JComboBox toAreaDropdown;
  private javax.swing.JLabel toAreaLabel;
  private javax.swing.JComboBox toBusStopDropdown;
  private javax.swing.JLabel toBusStopLabel;
  private javax.swing.JLabel toLabel;
  // End of variables declaration//GEN-END:variables

}
