/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LiveInfoInterface.java
 *
 * Created on May 1, 2012, 12:41:14 PM
 */

package ibms;

/**
 *
 * @author Ben
 */
public class LiveInfoInterface extends javax.swing.JFrame {

    /** Creates new form LiveInfoInterface */
    public LiveInfoInterface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busStopDropDown = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        routeDropDown = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        areaTextLabel = new javax.swing.JLabel();
        areaDropDown = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel1.setText("Live Information");

        jLabel2.setText("Bus Stop:");

        busStopDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        busStopDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busStopDropDownActionPerformed(evt);
            }
        });

        jLabel3.setText("Select your route:");

        routeDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        routeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeDropDownActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Time (HHMM):");

        timeField.setText("0000");
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        areaTextLabel.setText("Area:");

        areaDropDown.setModel(new javax.swing.DefaultComboBoxModel(BusStopInfo.getAreaNames()));
        areaDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaDropDownActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(timeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(submitButton))
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(25, 25, 25)
                        .add(routeDropDown, 0, 96, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(areaTextLabel))
                        .add(77, 77, 77)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(areaDropDown, 0, 96, Short.MAX_VALUE)
                            .add(busStopDropDown, 0, 96, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(areaTextLabel)
                            .add(areaDropDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(busStopDropDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(routeDropDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(timeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(submitButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_timeFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        //the bus stop we are going to use
        String busStopSelection = (String) busStopDropDown.getSelectedItem();

        //the route along which you are going to travel
        String route = (String) routeDropDown.getSelectedItem();

        

    }//GEN-LAST:event_submitButtonActionPerformed

    private void busStopDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busStopDropDownActionPerformed
        // TODO add your handling code here:
        busStopUpdate((String) busStopDropDown.getSelectedItem(), routeDropDown);
    }//GEN-LAST:event_busStopDropDownActionPerformed

    private void routeDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeDropDownActionPerformed

    private void areaDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaDropDownActionPerformed
        // TODO add your handling code here:
        areaUpdate((String) areaDropDown.getSelectedItem(), busStopDropDown);
    }//GEN-LAST:event_areaDropDownActionPerformed


    private void busStopUpdate(String busStop, javax.swing.JComboBox dropdown) {

        int [] routesAtBusStop = BusStopInfo.getRoutes();

        dropdown.removeAllItems();
        for (int i = 0; i < routesAtBusStop.length; i ++) {
            dropdown.addItem(routesAtBusStop[i]);
        }
    }

    private void areaUpdate(String area, javax.swing.JComboBox dropdown) {

        int areaNum = BusStopInfo.findAreaByName(area);
        int [] busStopsInArea = BusStopInfo.getBusStopsInArea(areaNum);

        dropdown.removeAllItems();
        for(int busStopId : busStopsInArea) {
            dropdown.addItem(BusStopInfo.getFullName(busStopId));
        }

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiveInfoInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areaDropDown;
    private javax.swing.JLabel areaTextLabel;
    private javax.swing.JComboBox busStopDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox routeDropDown;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables

}
